apiVersion: v1
kind: Service
metadata:
    name: {{ include "redis-cluster.headlessService" . }}
spec:
  clusterIP: None
  selector: {{ include "redis-cluster.selectRedisAll" . | nindent 4 }}
  ports:
  - port: 6379
    name: redis
