apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-redis-replica-sts
spec:
  selector:
    matchLabels: {{ include "redis-cluster.selectReplicaOnly" . | nindent 6 }}
  serviceName: {{ include "redis-cluster.headlessService" . }}
  replicas: {{ include "redis-cluster.replicaCount" . }}
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      initContainers:
        - name: init-redis
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
          args:
            - {{ .Values.fileConfigMapMountPath }}/init-replica.sh
          volumeMounts:
            - name: files
              mountPath: {{ .Values.fileConfigMapMountPath }}
            - name: redis-replica-config
              mountPath: {{ .Values.redisConfigFilePath }}
      containers:
        - name: {{ .Chart.Name }}-redis-replica
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
          args:
            - {{ .Values.fileConfigMapMountPath }}/start-redis.sh
          ports:
          - name: redis
            containerPort: 6379
          volumeMounts:
          - name: files
            mountPath: {{ .Values.fileConfigMapMountPath }}
          - name: redis-replica-config
            mountPath: {{ .Values.redisConfigFilePath }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            exec:
              command:
                - bash
                - {{ .Values.fileConfigMapMountPath }}/readiness-probe-redis.sh
            initialDelaySeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: files
          configMap:
            name: {{ include "redis-cluster.fileConfigMap" . }}
  volumeClaimTemplates:
  - metadata:
      name: redis-replica-config
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
