apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-redis-sentinel-sts
spec:
  selector:
    matchLabels: {{ include "redis-cluster.selectSentinelOnly" . | nindent 6 }}
  serviceName: {{ include "redis-cluster.headlessService" . }}
  replicas: {{ .Values.sentinels }}
  template:
    metadata:
      labels:
        app: redis
        role: sentinel
    spec:
      initContainers:
        - name: init-redis
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
          args:
            - {{ .Values.fileConfigMapMountPath }}/init-sentinel.sh
          volumeMounts:
            - name: files
              mountPath: {{ .Values.fileConfigMapMountPath }}
            - name: redis-sentinel-config
              mountPath: {{ .Values.redisConfigFilePath }}
      containers:
        - name: {{ .Chart.Name }}-redis-sentinel
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
          args:
            - {{ .Values.fileConfigMapMountPath }}/start-sentinel.sh
          ports:
          - name: redis
            containerPort: 6379
          volumeMounts:
          - name: files
            mountPath: {{ .Values.fileConfigMapMountPath }}
          - name: redis-sentinel-config
            mountPath: {{ .Values.redisConfigFilePath }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            exec:
              command:
                - bash
                - {{ .Values.fileConfigMapMountPath }}/readiness-probe-sentinel.sh
            initialDelaySeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: files
          configMap:
            name: {{ include "redis-cluster.fileConfigMap" . }}
  volumeClaimTemplates:
  - metadata:
      name: redis-sentinel-config
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
