apiVersion: v1
kind: Service
metadata:
    name: {{ .Chart.Name }}-loadbalancer
spec:
  type: LoadBalancer
  selector: {{ include "redis-cluster.selectMasterOnly" . | nindent 4 }}
  ports:
  - port: 36379
    targetPort: 6379
    name: redis
